### ISSUE TITLE
Hide git branch information when current file is untracked

### ISSUE THREAD

**Issue by Tummetott** [feline-nvim/feline.nvim#168]
Hello, 

I have a question i can't figure out: Is it possible to hide the `git_branch` provider, when the the current file is not tracked by git?

If my current working directory of nvim is inside a git repo, I'm always getting the branch information. Even if I open another file which is outside the working directory and not inside a git branch.

I mean I could do something like:
```
component = {      
    provider = 'git_branch',
    enabled = function ()
        local path = vim.fn.expand('%')
        -- From here pseudo code
        tracked_files = os.execute('git ls-files')
        if path in tracked_files do
            return true
        else
            return false
        end
        -- pseudo code end
    end,
}
```

But since this would require a system call, it does not seem very elegant. Can gitsigns be used to retrieve this information? or another trick?

Thanks a lot

**Comment by famiu** [comment]
I'm not sure if there's a way to find out if the current file is tracked or not through gitsigns, and I definitely would be against using system calls since they're not only inelegant but also potentially very insecure

**Comment by ram02z** [comment]
Setting the config option `attach_to_untracked` in gitsigns to `false` doesn't resolve this unfortunately.

**Comment by famiu** [comment]
Closing this issue since it's not currently possible to implement this without system calls. If someone does find a way though, either make a new issue that mentions the way or a PR that implements it
