### ISSUE TITLE
[Feature] Tabline support

### ISSUE THREAD

**Issue by jlesquembre** [feline-nvim/feline.nvim#169]
**Is your feature request related to a problem? Please describe.**
It would be nice if it had support for tabline, to make the statusline and the tabline consistent. 

**Additional context**
I found this discussion about the same topic for galaxyline: https://github.com/glepnir/galaxyline.nvim/issues/24
I fully agree with this comment: https://github.com/glepnir/galaxyline.nvim/issues/24#issuecomment-727907348

And thanks for feline.nvim, it's a great plugin, my neovim looks a lot better thanks to it :)

**Comment by FrenzyExists** [comment]
So uh, lets see if I can understand this, you mean that feline could also be a tabline? As in tapping this thingy?

![image](https://user-images.githubusercontent.com/47986470/143153492-240bd682-8025-4bab-bac8-2f4c3b0cc7ad.png)

**Comment by jlesquembre** [comment]
@FrenzyExists  yes, I'd like to customize what I can see on that screenshot, the tabline.

feline currently offers a nice api to customize the statusline, it'd be great to be able to use the same api to customize the tabline too

**Comment by FrenzyExists** [comment]
I've been checking the code in feline (note, I don't exactly know lua that much), and decided to also check akinsho's bufferline code. I think that lilke, maybe 1/4th of the utils from bufferline code from there could just be yoinked into feline, which is pretty much the clickable functions, the functions that comunicate with neovim's buffer and tabs, and the close button.

**Comment by famiu** [comment]
I'm not sure how to handle the tabline click events, so I'd have to look into it. A PR would also be very welcome.

**Comment by famiu** [comment]
It seems adding tabline support is much more complicated than it sounds and would require too much change to the original codebase and documentation to be worth the hassle. Besides, there's already quite a few good tabline plugins, so I'd just recommend using those. I'd like Feline to stick with the Unix philosophy of doing one thing and doing it well.

**Comment by Tummetott** [comment]
What a pitty. Feline is by far the best statusline plugin out there, the APi is just on point. The tabline plugins I know are:
barbar, bufferline, tabby and nvim-tabline. I tried them all and they have all their flaws. Anyway, I understand your decision, just wanted to note that configuring the tabline with the feline API would be a blast.
