### ISSUE TITLE
[Feature] Missing a utility function to get feedback whether a section is truncated or not

### ISSUE THREAD

**Issue by Tummetott** [feline-nvim/feline.nvim#170]
Hello, 

to start with: Thanks for this amazing plugin, i recently switched from galaxyline because of the amazing truncation system. You just define priorities and and feline does the rest, love it! But now I'll try to describe my problem.

Part of my statusline looks like this:
![grafik](https://user-images.githubusercontent.com/19708025/142608670-11dfd114-7647-47c5-af80-c0e6109990e5.png)

The section with the `file_info` provider is configured with `truncate_hide = true`. When I decrease my window size, this section gets truncated and it looks like this

![grafik](https://user-images.githubusercontent.com/19708025/142608948-fe153719-2d4a-41e1-aaa1-6051c2c056aa.png)

The Problem is the highlighting of the previous `right_rounded` separator (I circled it with red). I would like to highlight the `bg` of the `right_rounded` separator with grey, when the `file_info` section is not truncated. But I would like to highlight it with the color of my terminal background, when the `file_info` section is truncated. However, I don't find a good way to get feedback from feline whether a section is truncated of not. 

I looked in the code of `generator.lua` and found e.g. the table `local component_widths = {}` which hold all the lengths of the sections during statusline generation. When a section is truncated, the respective length is 0. I know it's not a good idea to expose this specific table to the user, but a utility function like `require('feline').is_truncated(section)` would solve this issue. The function argument `section` could be a simple index since sections are not named. 

I don't feel confident enougth to make a pull request and hope, that someone can help me with this.

Best Tummetott

**Comment by famiu** [comment]
I think a way better and more elegant solution would be to allow modifying the separators after truncation as well, like having a `short_separator` value, so you could change the highlight of that. Thoughts?

**Comment by Tummetott** [comment]
In this case, a `short_separator` would not help because highlighting of the separator depends on the truncation state of the **next** section. Of course you could think of moving the separator in question to the next section but than I still have the same problem, when the separator highlighting depends on the truncation state of the next **two** sections. Think of my example with the screenshots and imagine I want to put another provider in the grey bar after the `file_info` provider.

**Comment by famiu** [comment]
> In this case, a `short_separator` would not help because highlighting of the separator depends on the truncation state of the **next** section. Of course you could think of moving the separator in question to the next section but than I still have the same problem, when the separator highlighting depends on the truncation state of the next **two** sections. Think of my example with the screenshots and imagine I want to put another provider in the grey bar after the `file_info` provider.

I suppose that is true, but using the index to see if a component is truncated also seems a bit finicky imo, not that I can think of a much better alternative

**Comment by Tummetott** [comment]
How about adding an optional `name` attribute to each section table? The `hl` table already has a `name` attribute which is optional. The usage page states:
>Feline automatically generates a unique name for the highlight group based on the other values, so you can also just omit the name and Feline will create new highlights for you when required.

In contrast to the `name` attribute of the `hl` table, the new `name` attribute of the section table would not be generated at runtime. The default would be nil, and it is just changed when the user defines an explicit name in the confuguration. Therefore it would not affect the runtime.

Here an example:
````lua
table.insert(components.active[1], {
    provider = 'file_info',
    enabled = function ()
         if vim.fn.expand('%:t') ~= '' then return true end
    end,
    hl = 'StatusComponentFilename'
    name = 'FileInformation'
}
````

Later this `name` attribute can be used in a function like `require('feline').is_truncated('FileInformation')`.

The more I think if this problem, the more I want fine granular feedback about the truncation state. It would be of great use to know, if a section is either shortened by showing the `short_line`, completely hidden or none of the both. Therefore, insted of the `require('feline').is_truncated('FileInformation')` function, two functions like `require('feline').is_hidden('FileInformation')` and `require('feline').is_shortened('FileInformation')` would do the trick.

I know this feels like adding a lot to a simple and neat codebase but it would give sooo much more options to configure a dynamic statusline. I also think that naming sections could prove valuable for future features. It is a straightforward way to reference a section for whatever purpose.
