### ISSUE TITLE
[Feature] Update to vim.diagnostic.get (if possible)

### ISSUE THREAD

**Issue by flyingsl0ths** [feline-nvim/feline.nvim#178]
**Is your feature request related to a problem? Please describe.**
The import `feline.providers.lsp` causes the message
`vim.lsp.diagnostic.get_count is deprecated. See :h deprecated` to constantly popup in
the latest neovim nightly specifically under feline itself

**Describe the solution you'd like**
Update to `vim.diagnostic.get` as `:h deprecated` suggests

**Describe alternatives you've considered**
Find some way to silence the warning as it will not go away (if possible)

**Additional context**
EDIT: It seems #176 has mentioned this already as well and provided a solution

**Comment by famiu** [comment]
Closing this since #176 was merged
