### ISSUE TITLE
implement color groups suppport by default

### ISSUE THREAD

**Issue by RaafatTurki** [feline-nvim/feline.nvim#184]
This is more of a fix than a bug but here it goes.

## Issue
the theming system atm is a huge pain to deal with imo, here are my issues with it:
- using the default feline never looks like the rest of your neovim
- the need to define, add and use a theme for every colorscheme you have (and each of their variants) just to make feline look normal
- changing your colorscheme in runtime totally breaks feline

the theming system should be a nice addition for finer control not the default.

## Suggested Solution
feline could calculate its default theme on `VimEnter` by doing something like:
```lua
function get_col(group, id) return vim.fn.synIDattr(vim.fn.hlID(group), id) end

{
  fg = get_col('FelineMain', 'fg') or '#D0D0D0',
  bg = get_col('FelineMain', 'bg') or '#1F1F23',
  .
  .
  .
},
```
further more the autocmd `ColorScheme` can be used to recalcuate the theme so it stays up to date across colorscheme changes without user intervention.

If this is a welcome change I would take a crack at it and submit a PR.

**Comment by lukas-reineke** [comment]
I agree with this.
I even think we can go further, and just accept either hex color fg and bg, or a highlight group name.

**Comment by lukas-reineke** [comment]
I looked into implementing this, but it already is :sweat_smile: 

You can already use a highlight group instead of defining `fg`, `bg` and `style` yourself.
So instead of

```lua
{
    provider = 'file_info',
    hl = {
        fg = 'white',
        bg = 'oceanblue',
        style = 'bold',
    },
},
```

you can do

```lua
{
    provider = 'file_info',
    hl = "Comment",
},
```

And it should just work. Switching colorschemes as well.
