### ISSUE TITLE
bg color for statusline doesnt work 

### ISSUE THREAD

**Issue by siduck** [feline-nvim/feline.nvim#188]
After commit 6be9ca2d26b704d4df91a3199cd0c2ab870ac9d8, the bg color doesnt for whole statusline doesnt work. 
```
require("feline").setup {
   colors = {
      bg = "hexcolor",
   }
}
```
feline version = master 

https://user-images.githubusercontent.com/59060246/147126976-5a89efe5-2810-471c-b327-785f409ac850.mp4

It did work before

**Comment by MonstrousOgre** [comment]
`colors` has now been renamed to `theme`. See 47dc59e63d444d5e46e7c7aa7595ef6bba44e0b2
