### ISSUE TITLE
[Bug] invalid severity error for diagnostic provider

### ISSUE THREAD

**Issue by RaZ0rr-Two** [feline-nvim/feline.nvim#189]
**Neovim version**
The output of `nvim --version`.
<details>
<summary>nvim --version</summary>
NVIM v0.6.0
Build type: Release
LuaJIT 2.0.5
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
</details>

**Feline version**
master lastest

**Describe the bug**
Getting this warning message with feline config
```lua
Feline: error while processing component number 3 on section 2 of type 'a
ctive': /usr/share/nvim/runtime/lua/vim/diagnostic.lua:83: Invalid severi
ty: Warning
Press ENTER or type command to continue
Feline: error while processing component number 5 on section 2 of type 'a
ctive': /usr/share/nvim/runtime/lua/vim/diagnostic.lua:83: Invalid severi
ty: Information
```

**Additional context**
Error message disappears when the words `Warnings.` and `Information` to `Warn` and `Info` respectively.

Change this : 
```lua
components.active[2][3] = {
	provider = 'diagnostic_warnings',
	enabled = function() return lsp.diagnostics_exist('Warning') end,
	hl = {
		fg = 'yellow',
		style = 'bold'
	}
}
```

to
```lua
components.active[2][3] = {
	provider = 'diagnostic_warnings',
	enabled = function() return lsp.diagnostics_exist('Warn') end,
	hl = {
		fg = 'yellow',
		style = 'bold'
	}
}
```

**Comment by RaZ0rr-Two** [comment]
I think 
```lua
enabled = require('feline.providers.lsp').diagnostics_exist(vim.diagnostic.severity.WARN)
enabled = require('feline.providers.lsp').diagnostics_exist(vim.diagnostic.severity.INFO)
```
are better alternatives.

**Comment by lukas-reineke** [comment]
Yes, this was a breaking change in the latest release https://github.com/feline-nvim/feline.nvim/releases/tag/v0.4.0, sorry about that
