### ISSUE TITLE
[Bug] Feline: error while processing component number 6 on section 1 of type 'active': ...ck/packer/start/feline.nvim/ lua/feline/providers/lsp.lua:45: attempt to index upvalue 'diagnostic' (a nil value)

### ISSUE THREAD

**Issue by jalberto** [feline-nvim/feline.nvim#192]
**Neovim version**
0.5.1

**Feline version**
Master release

**Describe the bug**

**To Reproduce**
`Feline: error while processing component number 6 on section 1 of type 'active': ...ck/packer/start/feline.nvim/ lua/feline/providers/lsp.lua:45: attempt to index upvalue 'diagnostic' (a nil value)`

**Expected behavior**

**Does this error occur in the minimal init file?**
yes

**Comment by ram02z** [comment]
Can you post your feline config using Github gist or similar?

**Comment by lukas-reineke** [comment]
Should be fixed now
