### ISSUE TITLE
[Bug] git branch shown even if not inside git repo

### ISSUE THREAD

**Issue by xeluxee** [feline-nvim/feline.nvim#194]
**Neovim version**
NVIM v0.6.0
Build type: Release
LuaJIT 2.0.5

**Feline version**
29f5cbf

**Describe the bug**
Git branch is shown even if not inside git repo. It's even shown in empty buffers and in vim help!
This happens after opening a file belonging to a git repo

**To Reproduce**
1. Open a file in a git repo
2. Branch is shown correctly
3. Open another file NOT in a git repo
4. The branch is shown (but it shouldn't)

**Expected behavior**
Branch should disappear. This is caused by this code:
https://github.com/feline-nvim/feline.nvim/blob/29f5cbfcecf563df84ac3b0e31e54e7b23e5331f/lua/feline/providers/git.lua#L33-L36
Why does it check `vim.g.gitsigns_head`? Feline should check only current buffer to detect correctly if it belongs to a git repo.

And should we keep `vim.g.gitsigns_head` in the provider?
https://github.com/feline-nvim/feline.nvim/blob/29f5cbfcecf563df84ac3b0e31e54e7b23e5331f/lua/feline/providers/git.lua#L6-L8

So I think we should remove `vim.g.gitsigns_head` from these files

**Comment by Akianonymus** [comment]
It actually is showing info for current folder git if no valid files are opened.

**Comment by ram02z** [comment]
Good catch! I have `autochdir` enabled so I couldn't reproduce. It does make sense to check the git information for the current buffer only.

**Comment by xeluxee** [comment]
Hi @ram02z, I've tried to enable `autochdir` but the bug still remains for files that are already opened.
If I open a new file the branch isn't shown, but if I change buffer and then switch to the opened file the branch appears

**Comment by ram02z** [comment]
> Hi @ram02z, I've tried to enable `autochdir` but the bug still remains for files that are already opened.
> If I open a new file the branch isn't shown, but if I change buffer and then switch to the opened file the branch appears

Hmm strange. Does the linked PR fix the issue? The fix you described makes sense.
