### ISSUE TITLE
highlights don't inherit from previous element on list

### ISSUE THREAD

**Issue by Pranav-Badrinathan** [feline-nvim/feline.nvim#202]
I am pretty sure I am missing something, but I can't get my highlights to work properly.
![image](https://user-images.githubusercontent.com/40524763/148004957-8bd18e28-c074-4cd5-92c8-e9b1336e99fe.png)

Look at the right side. For some reason the colors don't flow to the next like you would expect. This makes sense, as the arrow ends are separators, but in the [README screenshots](https://github.com/feline-nvim/feline.nvim#screenshots) section, some users have managed to pull it off.

looking into [code](https://github.com/EdenEast/nyx/blob/8a9819e/config/.config/nvim/lua/eden/modules/ui/feline/init.lua) from EdenEast (The only one with such styling that has posted the code for it) I can't find much different from mine other than using highlighting groups rather than Hex codes for the `hl` value.

My statusline code can be found on [PasteBin](https://pastebin.com/1BW7Kzsd) as I don't have a dotfiles repo yet.

Thanks for your time!

**Comment by lukas-reineke** [comment]
By default the separator uses the global background color.
But you can overwrite this per separator, like so

```lua
left_sep = {
    str = 'slant_left',
    hl = {
        fg = 'oceanblue',
        bg = 'red'
    }
}
```

**Comment by Pranav-Badrinathan** [comment]
That was it! Fixed! I can't believe I didn't try to do that before posting here, but regardless, thanks a lot!

**Comment by lukas-reineke** [comment]
No problem, don't be afraid to ask! We are happy to help :rocket:
