### ISSUE TITLE
[Docs] Some hot-links don't work in feline.txt

### ISSUE THREAD

**Issue by kyoh86** [feline-nvim/feline.nvim#203]
Some hot-links don't work for example, `feline-manually-added-providers`.
It links to `Setup function` section in the USAGE.md, but is not working in feline.txt.

**Comment by kyoh86** [comment]
I have tried to fix it myself, but it may be difficult to solve this issue for me.
Link notation for helpdoc is not as flexible as Markdown.
For example, it is not possible to separate the label from the link anchor.
It may be necessary to either remove some links from helpdoc, or make the text different from Markdown.

**Comment by ram02z** [comment]
The docs are automatically generated using [panvimdoc](https://github.com/kdheepak/panvimdoc), so it will take some refactoring of the USAGE.md to fix the dead links.

**Comment by kyoh86** [comment]
@ram02z thanks for your advice!
I want to try to refactor the USAGE.md.

**Comment by ram02z** [comment]
> @ram02z thanks for your advice! I want to try to refactor the USAGE.md.

That would be great! Let me know once you submit a PR so I can review it.

**Comment by kyoh86** [comment]
It's difficult to resolve them.
Coz panvimdoc generates tags only for heading level 1 and 2...

**Comment by famiu** [comment]
This seems to be a limitation of vimdoc and so I've decided that it's not going to be fixed
