### ISSUE TITLE
Extraneous space in beginning of file_info provider

### ISSUE THREAD

**Issue by agorgl** [feline-nvim/feline.nvim#213]
Currently the returned value from file_info provider has an extra leading space, while other providers don't!
https://github.com/feline-nvim/feline.nvim/blob/e54e0cc5338b44d97dcaab83dd67d5a522656774/lua/feline/providers/file.lua#L124

**Comment by famiu** [comment]
that's to have a gap between the icon and the provider text

**Comment by agorgl** [comment]
The problem is that when the icon is disabled, the gap is still there!

**Comment by famiu** [comment]
should be fixed in #214
