### ISSUE TITLE
[Feature] Allow showing empty components with separators

### ISSUE THREAD

**Issue by agorgl** [feline-nvim/feline.nvim#216]
Feline is flexible enough to allow 'smart' scripting to add attributes in components.

In my setup, I define a table with the components, their options and their highlights, and with a for loop and some smart code I add the necessary separators. This allows components to be easily re-arranged (and moved to different sections) without the need to tweak the separators at all.

For decoration, I do have a single 'empty' component that gets populated with a single separator element, although currently empty provider strings do not show the given component.

I would love to see the separation of the condition on whether a component is shown by checking whether a provider is `nil` and not an empty string `''` thus allowing components with empty string providers to be shown and components with nil providers to be hidden (or the opposite, whatever the author thinks is better)

**Comment by famiu** [comment]
That's already possible with the `always_visible` key in separators
