### ISSUE TITLE
[Bug] Error when running PackerSync when using custom providers

### ISSUE THREAD

**Issue by agorgl** [feline-nvim/feline.nvim#229]
Having some `custom_providers` in my feline configuration, bellow error pops up each time I do `PackerSync`
```
"./lua/plugins.lua" 107L, 2628C written
packer.nvim: Error running config for feline.nvim: vim/_meta.lua:170: Vim:Feline: error while adding provider: Provider 'git_branch_dir' already exists! Please try using another name
```

**Comment by famiu** [comment]
it's probably an issue with Packer trying to reload the Feline lua modules, causing an error since Feline lua modules are not designed with reloadability in mind

**Comment by famiu** [comment]
Should be fixed now in the `develop` branch
