### ISSUE TITLE
[Feature] support/option for Global statusline

### ISSUE THREAD

**Issue by shaeinst** [feline-nvim/feline.nvim#242]
support for  Global statusline get [merged]( https://github.com/neovim/neovim/pull/17266) neovim.
i tried it with feline. works great, all we need is an option to toggle on/off global statusline.
split highlight also need to be fixed
![image](https://user-images.githubusercontent.com/41078534/158967581-05c05611-9627-4c5d-9fb1-44b88936f8c7.png)

**Comment by etrnal70** [comment]
Might be a problem with your colorscheme rather than feline i think. I think it's `VertSplit` highlight group

**Comment by famiu** [comment]
> Might be a problem with your colorscheme rather than feline i think. I think it's `VertSplit` highlight group

This, except `VertSplit` got superseded by `WinSeparator`

**Comment by famiu** [comment]
> support for Global statusline get [merged](https://github.com/neovim/neovim/pull/17266) neovim. i tried it with feline. works great, all we need is an option to toggle on/off global statusline. split highlight also need to be fixed ![image](https://user-images.githubusercontent.com/41078534/158967581-05c05611-9627-4c5d-9fb1-44b88936f8c7.png)

What's the point of adding an option in Feline when the user can do it themselves by setting the `laststatus` option

**Comment by shaeinst** [comment]
because i am using separate plugin for status line. that's the whole point of plugin. 
>  What's the point of adding an option in Feline when the user can do it themselves by setting the laststatus option

**Comment by famiu** [comment]
> because i am using separate plugin for status line. that's the whole point of plugin. 
> >  What's the point of adding an option in Feline when the user can do it themselves by setting the laststatus option

Hmm, I guess that's a valid point but setting `laststatus` is less complicated imho

**Comment by shaeinst** [comment]
true
>but setting laststatus is less complicated imho
it's always a nice to have options (if that not affect the performance ).

**Comment by famiu** [comment]
> true but it's always a nice to have options (if that not affect the performance ). 
> >but setting laststatus is less complicated imho
> 

Eh I just find it unnecessary to have two ways of using the same feature. Your Feline config will work perfectly fine regardless of what the value of `laststatus` is, so I'm going to leave it to the user to set that
