### ISSUE TITLE
[Bug] Cannot disable statusline using autocmd

### ISSUE THREAD

**Issue by etrnal70** [feline-nvim/feline.nvim#248]
**Neovim version**
v0.7.0-dev

**Feline version**
v1.1.2

**Describe the bug**
Trying to disable statusline using `laststatus=0` on `CmdlineEnter` event, but it doesn't work

I don't really know whether this is a Feline bug or not, but it works fine when using builtin neovim statusilne

**To Reproduce**
1.
```lua
vim.api.nvim_create_autocmd("CmdlineEnter", {pattern = "*", command = "set laststatus=0"})
vim.api.nvim_create_autocmd("CmdlineLeave", {pattern = "*", command = "set laststatus=3"})
```
2. Enter command mode (`:`)
3. Statusline not disabled

**Expected behavior**
Statusline disabled when entering commandline

**Does this error occur in the minimal init file?**
Yes

**Additional context**
My motivation for this is the upcoming `cmdheight=0` PR in neovim. I'm trying to make cmdline and statusline consume a single line by disabling statusline when in command mode and enable it back when leaving cmdline

**Comment by etrnal70** [comment]
Also tried using disable option, bufnames key in feline (based on https://vi.stackexchange.com/questions/14315/how-can-i-tell-if-im-in-the-command-window hint), still doesn't work too

**Comment by etrnal70** [comment]
Okay so i tried another statusline plugins (lualine.nvim and vim-airline) to see how it behaves and the result is none can be disabled. I think now it turns into a question instead of bug report. Is it possible to disable the statusline using autocmd ?

**Comment by etrnal70** [comment]
The closest hacks i can get is with 

```lua
vim.api.nvim_create_autocmd("CmdlineEnter", {pattern = "*",
  command = [[ set statusline= | redraws | set laststatus=0" ]]
)

vim.api.nvim_create_autocmd("CmdlineLeave", {
  pattern = "*", callback = function()
    require("feline").setup(config)
    vim.cmd("set laststatus=3")
    vim.cmd("redraws")
  end
})
```

But on the `CmdlineLeave` event i can't get feline back. It stuck on neovim statusline.

**Comment by etrnal70** [comment]
Btw, sadly i just realized that `laststatus=0` will keep showing statusline on non-last window :/

![image](https://user-images.githubusercontent.com/5826834/161432948-20025019-8809-4db7-8611-6f339076f02d.png)

My time are wasted lol

**Comment by lukas-reineke** [comment]
When you set `statusline` to nothing, it uses the default value.
Instead, try setting it to something you can't see, like a non-breaking space `set statusline= ` https://unicode-explorer.com/c/00A0

**Comment by etrnal70** [comment]
It would result in empty black bar like when i'm using the `disable` option in feline

https://user-images.githubusercontent.com/5826834/161459151-44ef6a71-9c90-4368-956b-c37a1b7719c9.mp4

**Comment by lukas-reineke** [comment]
You still need to set `laststatus=0` as well.

**Comment by etrnal70** [comment]
It will still show black bar on another horizontal split, just like `laststatus=0` would normally do. 

Is there a way to set a character to fill the whole statusline ? I want to set `statusline='-'` to emulate global statusline separator. I can then set `StatusLineNC guibg=NONE` on enter and set the value back when leaving to achieve my goal.

`statusline='-'` only fill the first character
![image](https://user-images.githubusercontent.com/5826834/161460543-87f4d5b6-ff65-43e3-8b95-3181d0f25406.png)

**Comment by lukas-reineke** [comment]
Ah yes, it does not work with `laststatus=3`. You didn't mention that you want to use that in the issue.

You could write a function to repeat `-`, or just set it to a very long string with `- `, but the result will not be 100% the same.
The edges will not look as nice as the proper win separator you get with `laststatus=3`

**Comment by etrnal70** [comment]
Yeah i mentioned it implicitly in the code, sorry about that. I guess removing the whole statusline is fine for now. Maybe new laststatus option or something can be introduced in the future to completely remove the statusline.

I'm using this for now 
```lua
vim.api.nvim_create_autocmd("CmdlineEnter", {
  pattern = "*",
  callback = function()
    vim.opt.laststatus = 0
    vim.opt.statusline = " "
    vim.cmd("hi StatusLineNC guibg=NONE")
    vim.cmd("redraws")
  end,
})
vim.api.nvim_create_autocmd("CmdlineLeave", {
  pattern = "*",
  callback = function()
    vim.cmd("hi StatusLineNC guibg=#1F1F1E")
    vim.opt.laststatus = 3
    require("feline").setup(config)
  end,
})
```

Thanks for your help !
