### ISSUE TITLE
[Bug] `file_info` provider doesn't display the right icon when buffer isn't linked to a file

### ISSUE THREAD

**Issue by xeluxee** [feline-nvim/feline.nvim#249]
**Neovim version**
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3

**Feline version**
Latest 290bea8e8a782586de32bb8d0bfb056ff8acdb9c

**Describe the bug**
I've used to set an icon for special buffers, buffers not associated with a file, like NvimTree buffer, Outline buffer, Trouble buffer...
To set an icon for certain buffers you can use this snippet:
``` lua
require("nvim-web-devicons").set_icon {
  NvimTree = {
    icon = " ",
    color = "#46b7e1",
    name = "NvimTree"
  },
}

```
But when I open NvimTree buffer I see normal file icon instead of the icon I've set. Previously it used to work but recently the icon is displayed wrongly.

**Expected behavior**
Display the icon set with `require("nvim-web-devicons").set_icon`

**Possible solution**
When the following line
https://github.com/feline-nvim/feline.nvim/blob/290bea8e8a782586de32bb8d0bfb056ff8acdb9c/lua/feline/providers/file.lua#L66
is replaced with
``` lua
    local extension = vim.bo.filetype
```
everything seems to work fine.

**Comment by famiu** [comment]
Fixed through #251

**Comment by famiu** [comment]
I reverted #251 since that's not the correct way to get extensions. I've decided I'm not going to support filetype icons for buffers not attached to a file by default, but I assume it shouldn't be too hard to make a custom provider that does that.

**Comment by xeluxee** [comment]
Before merging let us take some time to discuss, this issue is a bit complex
The change introduced with #251 works better for `CMakeLists.txt`, because it displays the gear icon (the correct one) instead of the common txt file icon
You can take as a comparison icons displayed in NvimTree
There are many different use cases and I think the design system of `nvim-web-devicons` should be improved because many plugins shows different icons on the same file due to api usage confusion (for example with the same `.bashrc` different icons are displayed in telescope, NvimTree and Feline :confounded:)

**Comment by famiu** [comment]
> Before merging let us take some time to discuss, this issue is a bit complex The change introduced with #251 works better for `CMakeLists.txt`, because it displays the gear icon (the correct one) instead of the common txt file icon You can take as a comparison icons displayed in NvimTree There are many different use cases and I think the design system of `nvim-web-devicons` should be improved because many plugins shows different icons on the same file due to api usage confusion (for example with the same `.bashrc` different icons are displayed in telescope, NvimTree and Feline confounded)

Then I think we should take the issue to `nvim-web-devicons`, and then I can make the changes required in Feline once that's dealt with

**Comment by xeluxee** [comment]
I think we don't need to get extension since `nvim-web-devicons` already gets it if not provided

https://github.com/kyazdani42/nvim-web-devicons/blob/4febe73506268a02ff15a240abcd7bf3eb9234da/lua/nvim-web-devicons.lua#L1374-L1386

And feline was failing in detecting buffer icons because the first argument of `require('nvim-web-devicons').get_icon_color` should be file name and not file path. Indeed the `filename` variable content is the full path (because `vim.api.nvim_buf_get_name(0)` returns full path and not only buffer name). So instead of using `nvim_buf_get_name` we should use `vim.fn.bufname()` because `nvim-web-devicons` looks for file name and ignores full paths (as you can see from the huge `icons` table in the file I've linked)

**Comment by famiu** [comment]
> I think we don't need to get extension since `nvim-web-devicons` already gets it if not provided
> 
> https://github.com/kyazdani42/nvim-web-devicons/blob/4febe73506268a02ff15a240abcd7bf3eb9234da/lua/nvim-web-devicons.lua#L1374-L1386
> 
> And feline was failing in detecting buffer icons because the first argument of `require('nvim-web-devicons').get_icon_color` should be file name and not file path. Indeed the `filename` variable content is the full path (because `vim.api.nvim_buf_get_name(0)` returns full path and not only buffer name). So instead of using `nvim_buf_get_name` we should use `vim.fn.bufname()` because `nvim-web-devicons` looks for file name and ignores full paths (as you can see from the huge `icons` table in the file I've linked)

I don't get what you mean, `vim.fn.bufname()` returns the same thing as `vim.api.nvim_buf_get_name(0)`

**Comment by xeluxee** [comment]
My bad, I've confused `vim.fn.bufname()` with `vim.fn.expand('%:t')`.
That's because `nvim_buf_get_name` (or `bufname`) sometimes returns full file path and not only file name, that is needed by `nvim-web-devicons` (see https://github.com/kyazdani42/nvim-web-devicons/blob/4febe73506268a02ff15a240abcd7bf3eb9234da/lua/nvim-web-devicons.lua#L1381)
