### ISSUE TITLE
[Bug] file_info provider not displaying the correct icons for .ts/.js files

### ISSUE THREAD

**Issue by igolt** [feline-nvim/feline.nvim#257]
**Neovim version**
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

**Feline version**
master branch (commit: 79f5e9e5a76842b72f1814dcd4fc239a95ead391)

**Describe the bug**
file_info does not display the correct icons for typescript/javascript files.

**To Reproduce**
You can use the minimal setup `require('feline').setup()` and open .js/.ts file

I think it can be fixed by changing:

lua/feline/providers/file.lua (line 66)
`local extension = bo.filetype`
to
`local extension = fn.expand('%:e')`

Thanks in advance

**Comment by famiu** [comment]
Can you reproduce this issue on the develop branch?

**Comment by igolt** [comment]
No, it works as expected on the develop branch.

**Comment by famiu** [comment]
Alright, I'll try to resolve the issue in the master branch within a few days. Until then, please use the develop branch. Sorry for the incovenience.

**Comment by famiu** [comment]
Should be fixed now
