### ISSUE TITLE
[Feature] reverse scrollbar

### ISSUE THREAD

**Issue by stumash** [feline-nvim/feline.nvim#258]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
desired: scrollbar provider reversed. should start with small sliver at top, grows towards bottom
current: starts with small sliver at bottom, grows towards top

**Describe alternatives you've considered**
n/a

**Additional context**
just seems more intuitive that the scrollbar provider's "animation" moves in the same direction as the scrolling through the file (i.e. downward)

**Comment by stumash** [comment]
this could be achieved by reversing the order of the scrollbar blocks
https://github.com/feline-nvim/feline.nvim/blob/master/lua/feline/providers/cursor.lua#L5

and reversing the colors fg and bg
https://github.com/feline-nvim/feline.nvim/blob/master/lua/feline/presets/default.lua#L141-L144

**Comment by stumash** [comment]
I'll try to submit a PR that is as clean as possible. I think this is the kind of thing that would be better as PR than a separate plugin, but you may disagree / I know you don't want bloat

**Comment by famiu** [comment]
I don't mind if someone implements this and puts a PR (be sure to target the develop branch, not master), but I don't really have the time to do it myself as of right now.
