### ISSUE TITLE
[Bug] `file_type` provider not respecting options

### ISSUE THREAD

**Issue by joshfrench** [feline-nvim/feline.nvim#259]
**Neovim version**
```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@BigSur

Features: +acl +iconv +tui
```
**Feline version**
`v1.1.3`

**Describe the bug**
The `file_type` provider isn't picking up the [options listed in the documentation](https://github.com/feline-nvim/feline.nvim/blob/master/USAGE.md#file-type).

**To Reproduce**
```
# init.vim:
set termguicolors

call plug#begin('~/.local/share/nvim/plugged')
Plug 'feline-nvim/feline.nvim'
call plug#end()

lua << EOF
require('feline').setup({
  components = {
    active = {{
      {
        provider = "file_type",
        filetype_icon = true,
        case = "lowercase"
      }
    }}
  }
})
EOF
```
`$ vim foo.go`

Statusline reads:
`GO`

**Expected behavior**
Based on the listed options, I was expecting the statusline to have a lowercase `go` with the gopher icon.

**Does this error occur in the minimal init file?**
Yes:
<details>
<summary>Modified minimal_init.lua</summary>

```
-- Minimal init file to run Feline with the most basic functionality
-- Run from Feline top-level directory using:
-- nvim --noplugin -u minimal_init.lua

local tmpdir

if vim.fn.has('win32') == 1 then
    tmpdir = os.getenv('TEMP')
else
    tmpdir = '/tmp'
end

local function load_plugins()
    local packer = require('packer')
    local use = packer.use

    packer.reset()
    packer.init({
        package_root = tmpdir .. '/nvim/site/pack',
        git = {
            clone_timeout = -1,
        },
    })

    use('wbthomason/packer.nvim')
    use({
        'famiu/feline.nvim',

        -- If you wish to use the develop branch, uncomment the next line
        -- branch = 'develop',

        -- If you wish to use a specific version of Feline, uncomment the next line
        -- tag = 'v0.1', -- replace 'v0.1' with your version number

        requires = {
            {
                'lewis6991/gitsigns.nvim',
                requires = { 'nvim-lua/plenary.nvim' },
                config = function()
                    require('gitsigns').setup()
                end,
            },
            'kyazdani42/nvim-web-devicons',
        },
    })

    packer.sync()
end

_G.load_config = function()
    vim.opt.termguicolors = true

    -- Replace this part of the config with whatever Feline configuration you're using
    require('feline').setup({
      components = {
        active = {{
          {
	    provider = "file_type",
	    filetype_icon = true,
	    case = "lowercase"
          }
        }}
      }
    })
end

local install_path = tmpdir .. '/nvim/site/pack/packer/start/packer.nvim'

vim.opt.packpath = { tmpdir .. '/nvim/site' }

if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({ 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path })
end

load_plugins()
vim.api.nvim_command('autocmd User PackerComplete ++once lua load_config()')
```
</details>

**Screenshots**
`init.vim`:
<img width="1266" alt="init vim" src="https://user-images.githubusercontent.com/4573/167033236-65f53e7c-5f6c-428f-ae5f-8bb6c4c98538.png">
`minimal_init.lua`:
<img width="1266" alt="minimal_init lua" src="https://user-images.githubusercontent.com/4573/167033286-51cc726f-c217-43e3-9eea-710600cb6569.png">

**Comment by ram02z** [comment]
Should be
```lua
  provider = {
    name = "file_type",
    opts = {
       case = "lowercase",
    },
  },
```

See https://github.com/feline-nvim/feline.nvim/blob/master/USAGE.md#component-providers for more information.``

**Comment by joshfrench** [comment]
That works, thank you! I was following the `vi-mode` example, which uses the syntax I tried originally. Out of curiosity, what's the difference between the two providers/syntaxes?

**Comment by ram02z** [comment]
> That works, thank you! I was following the `vi-mode` example, which uses the syntax I tried originally. Out of curiosity, what's the difference between the two providers/syntaxes?

I think the `opts` table method is new and the old method is deprecated. The old documentation should probably be updated.

**Comment by joshfrench** [comment]
Gotcha. Thanks!
