### ISSUE TITLE
[Bug] `file_info` does not respect `opts`

### ISSUE THREAD

**Issue by Diegovsky** [feline-nvim/feline.nvim#269]
**Neovim version**
```
NVIM v0.8.0-dev+253-geb0aa8bb0e
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/sbin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions     -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security     -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/main-builder/pkgwork/src/build/config -I/home/main-builder/pkgwork/src/neovim-git/src -I/usr/include -I/home/main-builder/pkgwork/src/build/src/nvim/auto -I/home/main-builder/pkgwork/src/build/include
Compiled by main-builder

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Feline version**
`master`, 3991842d2a57746e49a682e70f8b1f3929248868

**Describe the bug**
The `file_info` module does not respect it's `opts` module. I haven't tested other modules' `opts`
```lua
file = {
    info = {
      provider = "file_info",
      opts = {
        file_readonly_icon = '!'
      },
      hl = {
        fg = colors.blue,
        style = "bold",
      },
    },
  }
```

**To Reproduce**
1. Set any `opts` flag on `file_info`.
2. Setup your bar.

**Expected behavior**
The provider should change itself according to the options I set it up to do.

**Does this error occur in the minimal init file?**
Yes, see diff

**Provide modified minimal_init.lua**
I'll provide you a diff so you can see exactly what I have changed:
[repro.diff](https://github.com/feline-nvim/feline.nvim/files/8747839/repro.txt)

**Screenshots**
My config:
![image](https://user-images.githubusercontent.com/46163903/169657370-b8dce1c4-11ae-4a90-80b2-27253bff7759.png)

Reproduceable example (c.txt is a different file in every buffer):
![image](https://user-images.githubusercontent.com/46163903/169657337-9a1861ab-60be-44b1-93fb-5630e1fdaf89.png)

**Comment by famiu** [comment]
That's not how you use provider opts, see the example in https://github.com/feline-nvim/feline.nvim/blob/master/USAGE.md#component-providers

**Comment by Diegovsky** [comment]
I see, it seems that `provider` can be a table, right? Sorry for the mixup :)
