### ISSUE TITLE
[Bug] winbar doesn't update as I move the cursor

### ISSUE THREAD

**Issue by ahhshm** [feline-nvim/feline.nvim#270]
**Neovim version**
```
NVIM v0.8.0-dev+272-g5193b1783
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

**Feline version**
commit: [`3991842`](https://github.com/feline-nvim/feline.nvim/commit/3991842d2a57746e49a682e70f8b1f3929248868)

**Describe the bug**
I have a `context` provider that shows the context of the current cursor (`nvim-gps` provides the context):
```lua
  custom_providers = {
    context = function()
      return gps.get_location()
    end,
  },
```
When I use it in the statusline, it updates as I move the cursor so it shows the correct context. But when I use it in the winbar, it doesn't update at all. to be more precise, it just updates once and then i have to go to the insert mode and then back to the normal mode to trigger the `provider` and update the winbar.

winbar usage:
```lua
feline.winbar.setup({
  components = {
    active = {
      {
        {
          provider = {
            name = "context",
          },
          enabled = function()
            return gps.is_available()
          end,
        },
      },
    },
  },
})
```

**Comment by famiu** [comment]
That's a known Neovim bug that will hopefully be fixed by https://github.com/neovim/neovim/pull/18646

**Comment by ahhshm** [comment]
Thanks. so i close this

**Comment by famiu** [comment]
Let's keep it open until the mentioned PR is merged to prevent more issues like this
