### ISSUE TITLE
[Docs] How to actually use Feline

### ISSUE THREAD

**Issue by f0-x** [feline-nvim/feline.nvim#276]
**Describe what changes to the documentation you want**
For newbies like me, I have installed Feline via vim plug but I can't figure out how to actually start using it, my statusline hasn't changed.

**Comment by f0-x** [comment]
Forgot to wrap up my Lua configs within
```
lua << EOF
<config>
EOF
```

**Comment by A-F-V** [comment]
Could you elaborate? I have never used lua before but have downloaded feline with Plug

**Comment by ram02z** [comment]
> Could you elaborate? I have never used lua before but have downloaded feline with Plug

He is embedding the Lua script in VimScript, so in your vim config file (.vimrc or init.vim) you can add

```vim
lua << EOF
require('feline').setup()
EOF
```

This is will setup feline to use the default configuration
