### ISSUE TITLE
[Bug] Wired behavior with inline-highlights

### ISSUE THREAD

**Issue by ahhshm** [feline-nvim/feline.nvim#281]
**Neovim version**
```
NVIM v0.8.0-dev+368-gff20d4032
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```
**Feline version**
commit: [`1ea4267`](https://github.com/feline-nvim/feline.nvim/commit/1ea42671c523a080a01c62c40c2c8e7fc0139a8f)

**Describe the bug**
Today I've been playing with the winbar and inline-highlights and I found a wired behavior that may be a bug.
```lua
local the_component = {
  provider = "%#CmpItemKindClass# normal %* bold",
}

feline.setup({
  components = {
    active = {
      {
        the_component,
      },
    },
  },
})

feline.winbar.setup({
  components = {
    active = {
      {
        the_component,
      },
    },
  },
})

```
As you can see, I added the same component (`the_component`) to both the winbar and statusline. But the results are different:

![image](https://user-images.githubusercontent.com/87268103/172059057-584b6aee-f2ec-4d74-a32b-4347868c6b4f.png)

The characters after the inline highlight are bolded in the winbar!

**Comment by famiu** [comment]
That's just the default winbar highlight which you enabled using `%*`
