### ISSUE TITLE
Inherit theme fg and bg from given highlighting group

### ISSUE THREAD

**Issue by mitinarseny** [feline-nvim/feline.nvim#282]
I like feline for a lot of reasons, but when it comes to write colors in hex, it frustrates me.

I use https://github.com/arcticicestudio/nord-vim colorcheme, so when call `:colorscheme nord` all the colors are set from its [`colors/`](https://github.com/arcticicestudio/nord-vim/blob/main/colors/nord.vim) and they are not exposed to user except for global function `NordPalette()` which I don't want to depend on for a number of reasons.

It would be nice if feline could inherit `guibg` and `guifg` from given highlighting groups for all components, which do not explicitly provide `hl`:
```lua
require('feline').setup({
  theme = {
    bg = 'StatusLineNC',
    fg = 'Normal',
  },
})
```

**Comment by vladimir-popov** [comment]
it was suggested previously https://github.com/feline-nvim/feline.nvim/pull/167

**Comment by famiu** [comment]
Yeah, I have no intention of implementing this. Just use `nvim_get_hl_by_name`
