### ISSUE TITLE
Changing single option without needing to add whole config

### ISSUE THREAD

**Issue by laniusone** [feline-nvim/feline.nvim#296]
It might be a stupid question and I might be missing something.
What I want to do is to basically replace separators around file component, but I cannot find a way to do this other than putting whole default config in setup function with my little changes.
If that is the case, is full default config somewhere to just copy-paste?

**Comment by famiu** [comment]
The default components table can be found in: https://github.com/feline-nvim/feline.nvim/blob/master/lua/feline/default_components.lua

**Comment by laniusone** [comment]
OK, after figuring out which structure I need to put in setup method, it just worked. Thank you!
