### ISSUE TITLE
[Feature] Change the path seperator for the file_info provider

### ISSUE THREAD

**Issue by Nick-pr** [feline-nvim/feline.nvim#301]
**Is your feature request related to a problem? Please describe.**
As a user, I would like the ability to replace the path separators within a path when using the default provider `file_info`.

For example,
 this `foo/bar/test.lua`
 could be `foo > bar > test.lua`

**Describe the solution you'd like**
Usage could look something like this when defining a component:
```lua
{
  provider = {
    name = "file_info",
    opts = { path_sep = " > "}  
  }
}
```

**Describe alternatives you've considered**
I think the simplest and most intuitive way of implementing this is just by adding an option for the `file_info` provider

**Considerations**
- Should work correctly on both Windows and UNIX machines.

**Comment by famiu** [comment]
Thanks for opening the issue :)

I'll look into it as soon as I can
