### ISSUE TITLE
E542: Unbalanced groups

### ISSUE THREAD

**Issue by caenrique** [feline-nvim/feline.nvim#303]
I have this error from time to time, and I can't figure out why

```
E5108: Error executing lua ...e/pack/packer/start/feline.nvim/lua/feline/generator.lua:517: E542: unbalanced groups
stack traceback:
        [C]: in function 'nvim_eval_statusline'
        ...e/pack/packer/start/feline.nvim/lua/feline/generator.lua:517: in function 'get_component_width'
        ...e/pack/packer/start/feline.nvim/lua/feline/generator.lua:609: in function <...e/pack/packer/start/feline.nvim/lua/feline/generator.lua:526>
```

Do you have any idea about the source of the problem??
my configs can be found [here](https://github.com/caenrique/nvim-config)

_Originally posted by @caenrique in https://github.com/feline-nvim/feline.nvim/discussions/292_

**Comment by ram02z** [comment]
The link to your config is broken

**Comment by caenrique** [comment]
Sorry, I updated the link to a public repository 😅 
[here](https://github.com/caenrique/nvim-config) is the link as well

**Comment by famiu** [comment]
can you comment out components one by one until you find out which component is causing this

**Comment by caenrique** [comment]
I think it's related with [this component](https://github.com/caenrique/nvim-config/blob/master/lua/caenrique/feline/components.lua#L117) (coming from [nvim-metals](https://github.com/scalameta/nvim-metals/blob/main/doc/metals.txt#L105)) which is text coming from a global variable and is has variable lenght. My guess is that when this texts doesn't fit, it crashes.

**Comment by caenrique** [comment]
I managed to isolate a generated statusline string that make `vim.api.nvim_eval_statusline` fail:
```
"%#StatusComponent_CDD6F4_313244_NONE#Compiling subscriptions 5s (0%)%#StatusComponent_NONE_313244_NONE# "
```
posibly because of the `%` sign?

**Comment by famiu** [comment]
I'm guessing that the provider string has unescaped `%` characters which can mess things up. You should probably escape those `%`s manually in that case

**Comment by kcsapp** [comment]
I was seeing the same errors (also from nvim-metals statuses) and was able to escape the '%' escape character successfully (from lua) with `s:gsub("[%%]", "%%%1")` - you might need to escape `#` in that line as well, like `s:gsub("[%%%#]", "%%%1")`.

**Comment by famiu** [comment]
Closing this as it is not a Feline issue.
