### ISSUE TITLE
[Bug]  adding 'neo-tree' to force-inactive table has no effect

### ISSUE THREAD

**Issue by thalha-dev** [feline-nvim/feline.nvim#305]
**Neovim version**
NVIM v0.7.0

local force_inactive = {
	filetypes = {
		"^neo-tree$",
		"^dbui$",
		"^packer$",
		"^startify$",
		"^fugitive$",
		"^fugitiveblame$",
		"^qf$",
	},
	buftypes = {
		"^terminal$",
	},
	bufnames = {},
}

**Comment by famiu** [comment]
Did you check whether the buffer filetype is actually named "neo-tree"

**Comment by thalha-dev** [comment]
![image](https://user-images.githubusercontent.com/76985723/190137106-dd37683e-c412-48aa-9b25-5776bbacaebb.png)
I tried : lua print(vim.bo.filetype)

**Comment by thalha-dev** [comment]
> You need to escape the hyphen with a `%` sign. Like `"^neo%-tree$"`

Thanks for your help
