### ISSUE TITLE
[Feature] An option for a small clock in the status bar

### ISSUE THREAD

**Issue by PumpedSardines** [feline-nvim/feline.nvim#314]
**Is your feature request related to a problem? Please describe.**
I often program with my IDE in fullscreen mode and i usually can't see the time. It would be nice to be able to see what time it is from my editor. 

**Describe the solution you'd like**
An option to display a small clock in either pm/am or 24 format in the little status bar.

**Describe alternatives you've considered**
Not sure what would be an alternative solution

**Additional context**
Nothing really

**Comment by famiu** [comment]
Eh, I don't see why it should be hard to implement a provider for it yourself. This also feels like a very niche usecase and goes against Feline's design goals of not adding too many things, so I'm going to have to shoot this idea down, sorry.
