### ISSUE TITLE
[Bug] cmdheight=0 not working 

### ISSUE THREAD

**Issue by shaeinst** [feline-nvim/feline.nvim#315]
**Neovim version**
v0.8.0

**Feline version**
master branch 

**Describe the bug**
cmdheight=0 totally hides the status line. it was working fine when neovim v0.8.0 was in dev 

**To Reproduce**
1. set vim.opt.cmdheight=0'
2. open  neovim
3. there would be no status line.

**Expected behavior**
statusline should be visible when cmdheight=0

**this config won't work**
```lua
local import_feline, feline = pcall(require, 'feline')
if not import_feline then return end

local api = vim.api
local components = {active = {}, inactive = {}}
vim.opt.termguicolors = true -- Enable GUI colors for the terminal to get truecolor

components.active[1] = {
	{
		provider = function ()
			local mode = api.nvim_exec('echo mode()', true)
			if mode == "" then return "C" end
			return string.upper(mode)
		end,
	},
}
feline.setup({ components = components })
```

**Comment by famiu** [comment]
Does statusline appear with `nvim --clean`? What made you assume it's an issue with Feline and not a general statusline issue?

**Comment by famiu** [comment]
Okay so I looked into it, it's actually intended behavior for command line to override the last screen line of Neovim regardless of what's in it while you're typing a command, but the statusline should reappear when you aren't typing a command. If that's what's happening to you, then that's intended behavior and it's set by Neovim itself and Feline has nothing to do with it.

**Comment by shaeinst** [comment]
because following config works
```lua
require("feline").setup()
```

>Does statusline appear with nvim --clean? What made you assume it's an issue with Feline and not a general statusline issue with cmdheight=0

**Comment by shaeinst** [comment]
also when i tested feline last time with v0.8, everything was working fine

**Comment by famiu** [comment]
I can't reproduce your issue with the `minimal_init.lua`. Can you try modifying the `minimal_init.lua` and use it with `nvim --clean -u minimal_init.lua` to see if it works

**Comment by shaeinst** [comment]
could you please test with the snippet i mentioned.
```lua
-- require("feline").setup()
local import_feline, feline = pcall(require, 'feline')
if not import_feline then return end

local api = vim.api
local components = {active = {}, inactive = {}}
vim.opt.termguicolors = true -- Enable GUI colors for the terminal to get truecolor

components.active[1] = {
	{
		provider = function ()
			local mode = api.nvim_exec('echo mode()', true)
			if mode == "" then return "C" end
			return string.upper(mode)
		end,
	},
}
feline.setup({ components = components })

```

as i mentioned, `require("feline").setup()` works fine for me too. But passing 
components as 
```lua
components.active[1] = {
	{
		provider = function ()
			local mode = api.nvim_exec('echo mode()', true)
			if mode == "" then return "C" end
			return string.upper(mode)
		end,
	},
}
```
makes statusline hidden

**Comment by famiu** [comment]
Yes and I can't reproduce your config with the `minimal_init.lua` modified to use it. Can you please follow the instructions and use the `minimal_init.lua` but replace `require('feline').setup()` with your config and run it with `nvim --clean -u minimal_init.lua` and see if the issue still occurs.

**Comment by shaeinst** [comment]
did what is asked for. problem remains the same

```lua
-- this template is borrowed from nvim-lspconfig
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
    local path_sep = on_windows and "\\" or "/"
    local result = table.concat({ ... }, path_sep)
    return result
end

vim.g.loaded_remote_plugins = ""
vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir = vim.loop.os_getenv("TEMP") or "/tmp"

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local null_ls_config = function()
    local null_ls = require("null-ls")
    -- add only what you need to reproduce your issue
    null_ls.setup({
        sources = {},
        debug = true,
    })
end

local feline_config = function ()
    local feline = require('feline')
    local components = {active = {}, inactive = {}}
    vim.opt.termguicolors = true -- Enable GUI colors for the terminal to get truecolor
    components.active[1] = {
        {
            provider = function ()
                local mode = vim.api.nvim_exec('echo mode()', true)
                if mode == "" then return "C" end
                return string.upper(mode)
            end,
        },
    }
    feline.setup({ components = components })
end


local function load_plugins()
    -- only add other plugins if they are necessary to reproduce the issue
    require("packer").startup({
        {
            "wbthomason/packer.nvim",
            {
                "jose-elias-alvarez/null-ls.nvim",
                requires = { "nvim-lua/plenary.nvim" },
                config = null_ls_config,
            },
            {
                'feline-nvim/feline.nvim',
                config = feline_config,
            }

        },
        config = {
            package_root = package_root,
            compile_path = compile_path,
        },
    })
end

if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
    load_plugins()
    require("packer").sync()
else
    load_plugins()
    require("packer").sync()
end

```

**Comment by famiu** [comment]
> did what you asked for. problem remains the same
> 
> ```lua
> -- this template is borrowed from nvim-lspconfig
> local on_windows = vim.loop.os_uname().version:match("Windows")
> 
> local function join_paths(...)
>     local path_sep = on_windows and "\\" or "/"
>     local result = table.concat({ ... }, path_sep)
>     return result
> end
> 
> vim.g.loaded_remote_plugins = ""
> vim.cmd([[set runtimepath=$VIMRUNTIME]])
> 
> local temp_dir = vim.loop.os_getenv("TEMP") or "/tmp"
> 
> vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))
> 
> local package_root = join_paths(temp_dir, "nvim", "site", "pack")
> local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
> local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")
> 
> local null_ls_config = function()
>     local null_ls = require("null-ls")
>     -- add only what you need to reproduce your issue
>     null_ls.setup({
>         sources = {},
>         debug = true,
>     })
> end
> 
> local feline_config = function ()
>     local feline = require('feline')
>     local components = {active = {}, inactive = {}}
>     vim.opt.termguicolors = true -- Enable GUI colors for the terminal to get truecolor
>     components.active[1] = {
>         {
>             provider = function ()
>                 local mode = vim.api.nvim_exec('echo mode()', true)
>                 if mode == "" then return "C" end
>                 return string.upper(mode)
>             end,
>         },
>     }
>     feline.setup({ components = components })
> end
> 
> 
> local function load_plugins()
>     -- only add other plugins if they are necessary to reproduce the issue
>     require("packer").startup({
>         {
>             "wbthomason/packer.nvim",
>             {
>                 "jose-elias-alvarez/null-ls.nvim",
>                 requires = { "nvim-lua/plenary.nvim" },
>                 config = null_ls_config,
>             },
>             {
>                 'feline-nvim/feline.nvim',
>                 config = feline_config,
>             }
> 
>         },
>         config = {
>             package_root = package_root,
>             compile_path = compile_path,
>         },
>     })
> end
> 
> if vim.fn.isdirectory(install_path) == 0 then
>     vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
>     load_plugins()
>     require("packer").sync()
> else
>     load_plugins()
>     require("packer").sync()
> end
> ```

I don't believe null-ls is part of the minimal config. Can you keep just Feline and not any of the other plugins?

Also, if it still occurs for you, then that's strange because I can't reproduce the error with the config you shared above with `minimal_init.lua`

**Comment by shaeinst** [comment]
as you can seen on screen record, scrolling up and down make status line visible for some ms. 

![output](https://user-images.githubusercontent.com/41078534/193447782-f2b898a5-dda2-4c3f-84e0-9c90777e8c51.gif)

**Comment by famiu** [comment]
I used this modification of `minimal_init.lua` and couldn't reproduce the issue:
```lua
-- Minimal init file to run Feline with the most basic functionality
-- Run from Feline top-level directory using:
-- nvim --noplugin -u minimal_init.lua

local tmpdir

if vim.fn.has('win32') == 1 then
    tmpdir = os.getenv('TEMP')
else
    tmpdir = '/tmp'
end

local function load_plugins()
    local packer = require('packer')
    local use = packer.use

    packer.reset()
    packer.init {
        package_root = tmpdir .. '/nvim/site/pack',
        git = {
            clone_timeout = -1,
        },
    }

    use('wbthomason/packer.nvim')
    use {
        'famiu/feline.nvim',
        requires = {
            {
                'lewis6991/gitsigns.nvim',
                requires = { 'nvim-lua/plenary.nvim' },
                config = function()
                    require('gitsigns').setup()
                end,
            },
            'kyazdani42/nvim-web-devicons',
        },
    }

    packer.sync()
end

_G.load_config = function()
    vim.o.termguicolors = true

    local import_feline, feline = pcall(require, 'feline')
    if not import_feline then return end

    local api = vim.api
    local components = {active = {}, inactive = {}}
    vim.opt.termguicolors = true -- Enable GUI colors for the terminal to get truecolor

    components.active[1] = {
            {
                    provider = function ()
                            local mode = api.nvim_exec('echo mode()', true)
                            if mode == "" then return "C" end
                            return string.upper(mode)
                    end,
            },
    }
    feline.setup({ components = components })
end

local install_path = tmpdir .. '/nvim/site/pack/packer/start/packer.nvim'

vim.o.packpath = tmpdir .. '/nvim/site'

if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
end

load_plugins()
vim.api.nvim_command('autocmd User PackerComplete ++once lua load_config()')
```

Also what you're using in the screen recording isn't a minimal init. Did you use `nvim --clean u minimal_init.lua` like I told you to?

**Comment by shaeinst** [comment]
I'm tired now. hope i'm the only one facing this problem...
