### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by langonginc** [feline-nvim/feline.nvim#326]
**Neovim version**

```
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local
```

**Describe the bug**

I added `require('feline').setup()` to `init.vim`, and I restart the Neo-vim.

<img width="922" alt="image" src="https://user-images.githubusercontent.com/59787082/200995330-6b3fc7e4-65b9-4217-8c74-9d280717a58e.png">

```
Error detected while processing /Users/wjy/.config/nvim/init.vim:
line   58:
E492: Not an editor command: require('feline').setup()
```

<img width="682" alt="image" src="https://user-images.githubusercontent.com/59787082/200995285-45c01a11-8090-4836-bc9f-6cdf878a6374.png">

I don't know if I added the line to a wrong file.

> **Does this error occur in the minimal init file?**
> Use the following commands to download the minimal init file provided by Feline:
> `curl -fLO https://raw.githubusercontent.com/feline-nvim/feline.nvim/master/minimal_init.lua`
> 
> Modify the file to your needs (if necessary), then load Neovim using:
> `nvim --noplugin -u minimal_init.lua`
> 
> And check if your issue still occurs.

I didn't got any output (just a blank window).

**Comment by famiu** [comment]
Did you use `:PlugInstall` to actually Feline?

**Comment by famiu** [comment]
> Since you're using init.vim, you've to use `lua require('feline').setup()`.

Right, that part slipped my mind as well.

Anyway, closing this issue. Please try to at least put minimal effort into solving your problems before opening an issue like this next time.

**Comment by langonginc** [comment]
Thank you very much, QAQ!
