### ISSUE TITLE
[Bug] Starting Error

### ISSUE THREAD

**Issue by corgile** [feline-nvim/feline.nvim#328]
## running nvim, getting error like: 

<img width="910" alt="image" src="https://user-images.githubusercontent.com/48396880/201484060-c35fea6a-3b79-412c-bee6-290cdcca7cfa.png">

## Please fix this, thank you

<img width="1375" alt="image" src="https://user-images.githubusercontent.com/48396880/201484090-a3995b48-0241-417a-8e31-d43abb6fb44e.png">

## my device:

<img width="280" alt="image" src="https://user-images.githubusercontent.com/48396880/201484133-eb5bc23a-225a-4673-b925-f84429587c74.png">

**Comment by LucasTavaresA** [comment]
sorry for being slow, i recently implemented this feature.
can you test this in my fork?
https://github.com/LucasTavaresA/feline.nvim
