### ISSUE TITLE
[Bug] Global function `module` gets overwritten by feline

### ISSUE THREAD

**Issue by calops** [feline-nvim/feline.nvim#335]
The global `module` lua function gets overwritten with a feline-specific table during setup. This breaks other plugins which rely on this function, and is in general very weird behavior for a plugin.

See `:h luaref-module` for more information on this function.

The responsible lines are there: https://github.com/feline-nvim/feline.nvim/blob/573e6d1e213de976256c84e1cb2f55665549b828/lua/feline/init.lua#L131-L137

**Comment by famiu** [comment]
This is unintentional. A local variable should've been used instead. Thanks for pointing it out
